// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB773CeHM9qlxlRQXBIBUEapmZVMc9VrHI',
    appId: '1:942880134560:web:df516c6e2b890e453400c5',
    messagingSenderId: '942880134560',
    projectId: 'crypto-wallet-4051a',
    authDomain: 'crypto-wallet-4051a.firebaseapp.com',
    storageBucket: 'crypto-wallet-4051a.appspot.com',
    measurementId: 'G-V09JK2LTR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlr2Zr4EuNVL2U924wXB97Xo-x0-O4JE',
    appId: '1:942880134560:android:957da3db5a901d123400c5',
    messagingSenderId: '942880134560',
    projectId: 'crypto-wallet-4051a',
    storageBucket: 'crypto-wallet-4051a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxfDQ1ERj0ue3kLccLC519EL_VwMaksk0',
    appId: '1:942880134560:ios:df06c62f3313518d3400c5',
    messagingSenderId: '942880134560',
    projectId: 'crypto-wallet-4051a',
    storageBucket: 'crypto-wallet-4051a.appspot.com',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxfDQ1ERj0ue3kLccLC519EL_VwMaksk0',
    appId: '1:942880134560:ios:c8ddc4e4b865dfb23400c5',
    messagingSenderId: '942880134560',
    projectId: 'crypto-wallet-4051a',
    storageBucket: 'crypto-wallet-4051a.appspot.com',
    iosBundleId: 'com.example.cryptoApp.RunnerTests',
  );
}
